name: tagpr
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tagpr:
    runs-on: ubuntu-24.04
    if: github.repository == 'sushichan044/memo-cli'
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: ./.github/workflows/composite/setup
        with:
          go-version-file: go.mod

      - uses: Songmu/tagpr@7191605433b03e11b313dbbc0efb80185170de4b # v1.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # tagpr guess version from label, but we need to guess it from conventional commit.
      - name: Get next version from svu
        id: svu
        run: |
          next_version="$(go run github.com/caarlos0/svu/v3@latest next)"
          if [ $? -ne 0 ]; then
            echo "::error::Failed to get the next version using svu"
            exit 1
          fi
          echo "next=$next_version" >> "$GITHUB_OUTPUT"

      - name: Switch to PR
        id: switch-to-pr
        run: |
          # Stash including untracked files to prevent "would be overwritten by checkout" errors
          git stash push -u -m "pre-switch-to-pr" || true
          PR_NUMBER=$(gh pr list --author "github-actions[bot]" --state 'open' --json 'number,headRefName' --jq '.[] | select(.headRefName | startswith("tagpr-from")) | .number')

          if [ -z "$PR_NUMBER" ]; then
            echo "::notice::No PR found."
            echo "should-continue=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # Try checkout to the PR branch; if it still fails for some reason, show diagnostics
          if ! gh pr checkout "$PR_NUMBER"; then
            echo "::error::Failed to checkout PR #$PR_NUMBER"
            git status --porcelain || true
            exit 1
          fi

          echo "should-continue=true" >> "$GITHUB_OUTPUT"
          echo "pr-number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Edit version file and commit and push
        if: steps.switch-to-pr.outputs.should-continue == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          sed -i "s/Version = \".*\"/Version = \"${{ steps.svu.outputs.next }}\"/" version/version.go

          if git diff --exit-code; then
            echo "::notice::No changes to version file"
            exit 0
          fi

          git add version/version.go
          git commit -m "chore: bump version to ${{ steps.svu.outputs.next }}"
          git push

          gh pr edit "${{ steps.switch-to-pr.outputs.pr-number }}" --title "Release for v${{ steps.svu.outputs.next }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
