name: tagpr
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tagpr:
    runs-on: ubuntu-24.04
    if: github.repository == 'sushichan044/memo-cli'
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: ./.github/workflows/composite/setup
        with:
          go-version-file: go.mod

      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - uses: Songmu/tagpr@7191605433b03e11b313dbbc0efb80185170de4b # v1.9.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      # tagpr guess version from label, but we need to guess it from conventional commit.
      - name: Get next version from svu
        id: svu
        run: |
          next_version="$(go run github.com/caarlos0/svu/v3@latest next)"
          if [ $? -ne 0 ]; then
            echo "::error::Failed to get the next version using svu"
            exit 1
          fi
          echo "next=$next_version" >> "$GITHUB_OUTPUT"

      - name: Get PR branch
        id: get-pr-branch
        run: |
          # Stash including untracked files to prevent "would be overwritten by checkout" errors
          git stash push -u -m "pre-switch-to-pr" || true
          PR_NUMBER=$(gh pr list --author "github-actions[bot]" --state 'open' --json 'number,headRefName' --jq '.[] | select(.headRefName | startswith("tagpr-from")) | .number')

          if [ -z "$PR_NUMBER" ]; then
            echo "::notice::No PR found."
            echo "should-continue=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          PR_BRANCH=$(gh pr view "$PR_NUMBER" --json headRefName --jq '.headRefName')

          echo "should-continue=true" >> "$GITHUB_OUTPUT"
          echo "pr-number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
          echo "pr-branch=$PR_BRANCH" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Edit version file
        if: steps.get-pr-branch.outputs.should-continue == 'true'
        run: |
          sed -i "s/Version = \".*\"/Version = \"${{ steps.svu.outputs.next }}\"/" version/version.go

      - name: Commit and push changes
        id: commit-and-push
        if: steps.get-pr-branch.outputs.should-continue == 'true'
        uses: suzuki-shunsuke/commit-action@594ab8a77a09357afe86bca600a98ab4b3b9547e # v0.0.13
        with:
          branch: ${{ steps.get-pr-branch.outputs.pr-branch }}
          files: |
            version/version.go
          commit_message: "chore: bump version to v${{ steps.svu.outputs.next }}"
          fail_on_self_push: false # push to current PR branch
          github_token: ${{ steps.app-token.outputs.token }}

      - name: Modify PR body
        if: steps.get-pr-branch.outputs.should-continue == 'true' && steps.commit-and-push.outputs.pushed == 'true'
        run: |
          gh pr edit "${{ steps.get-pr-branch.outputs.pr-number }}" --title "Release for v${{ steps.svu.outputs.next }}"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
